language: python
sudo: false
os:
  - linux
python:
  - "3.7"
  - "3.8"
  - "3.9"
notifications:
    email: false
install:
  - pip install .
script:
  - python build.py check all $FLAGS
env:
  - FLAGS=-j10
  - FLAGS=-j1
